Running in wrapper mode for '0'

Running python job.

[u'm1'] [u'small'] [2]
terasort
/home/vode/pj/cherrypick-sandbox/spearmint/examples/typeba/experiment.txt
experiment:  <Experiment 1 name='terasort' count=0>
runs:  [<Run 201 expID=1 configID=41 time=162.37 num=1>]
testdfsio
/home/vode/pj/cherrypick-sandbox/spearmint/examples/typeba/experiment.txt
experiment:  <Experiment 2 name='testdfsio' count=0>
runs:  [<Run 202 expID=2 configID=41 time=69.69 num=0>]
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=0>
<Run 202 expID=2 configID=41 time=69.69 num=1>
tpcds
/home/vode/pj/cherrypick-sandbox/spearmint/examples/typeba/experiment.txt
experiment:  <Experiment 5 name='tpcds' count=0>
runs:  [<Run 203 expID=5 configID=41 time=-1.0 num=1>]
----------------------------------------
Problem running the job:
(<type 'exceptions.Exception'>, Exception('Some errors when running!',), <traceback object at 0x7fa95d374878>)
Traceback (most recent call last):
  File "/home/vode/pj/cherrypick-sandbox/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/vode/pj/cherrypick-sandbox/spearmint/spearmint/runner.py", line 137, in run_python_job
    result = module.main(job.id, params)
  File "/home/vode/pj/cherrypick-sandbox/spearmint/examples/typeba/typeba.py", line 93, in main
    return COST_FUNC(get_cost(params))
  File "/home/vode/pj/cherrypick-sandbox/spearmint/examples/typeba/typeba.py", line 78, in get_cost
    raise Exception("Some errors when running!")
Exception: Some errors when running!
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 105.20 seconds.
