Running in wrapper mode for '20013'

Running python job.

[u'c3'] [u'small'] [2]
testdfsio
/home/vode/pj/cherrypick-sandbox/spearmint/examples/typeda/experiment.txt
experiment:  <Experiment 2 name='testdfsio' count=0>
runs:  []
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=0.0 num=0>
<Run 214 expID=2 configID=44 time=-1.0 num=1>
----------------------------------------
Problem running the job:
(<type 'exceptions.Exception'>, Exception('Some errors when running!',), <traceback object at 0x7f345190e950>)
Traceback (most recent call last):
  File "/home/vode/pj/cherrypick-sandbox/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/vode/pj/cherrypick-sandbox/spearmint/spearmint/runner.py", line 137, in run_python_job
    result = module.main(job.id, params)
  File "/home/vode/pj/cherrypick-sandbox/spearmint/examples/typeda/typeda.py", line 93, in main
    return COST_FUNC(get_cost(params))
  File "/home/vode/pj/cherrypick-sandbox/spearmint/examples/typeda/typeda.py", line 78, in get_cost
    raise Exception("Some errors when running!")
Exception: Some errors when running!
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 75.10 seconds.
